### ISSUE TITLE
Gem: can't load library

### ISSUE THREAD

**Issue by andreobar** [agraef/purr-data#1]
Many thanks for this port of Pd-l2ork. 
I get message "Gem: can't load library" on startup of purr-data on Mac OS/X. All other libraries work well. Is this due to the fact that this is a 64bit version? 
In effect, GEM 0.93.3 release notes state  "there are no native x86_64 (aka MacIntel 64bit) binaries available, so you must use a version of Pd that is i386 (32bit) compatible." https://puredata.info/downloads/gem/releases/0.93.3
On my 32bit version of pd-0.47-1 , GEM works.
Would you, by chance, have a 32bit build of purr-data or another solution?

**Comment by agraef** [comment]
> Would you, by chance, have a 32bit build of purr-data or another solution?

Nope, sorry, we only do 64 bit builds right now.

You may want to raise this issue upstream at https://git.purrdata.net/jwilkes/purr-data.
