### ISSUE TITLE
OBS repos only show i386 releases on Ubuntu 18.04 Bionic amd64 architecture

### ISSUE THREAD

**Issue by mark-orion** [agraef/purr-data#11]
I followed the instructions to set up the OBS repos for xUbuntu 18.04. I only see the PurrData and
Pd-L2ork for i386 architecture showing up in the package manager. This does not change if I use  deb [arch=amd64] ...
Manually downloading and installing the individual 64bit packages does work without any problems.

**Comment by agraef** [comment]
Sorry for the late reply, I'm just cleaning up very old bug reports after reopening the issue tracker. :) I think that this must have been fixed by now, so closing. Feel free to reopen the issue if it persists.
