### ISSUE TITLE
installing on Fedora

### ISSUE THREAD

**Issue by slyholborn** [agraef/purr-data#12]
Hello! I've managed to compile it on fedora but it gives a jack error a if jack was not installed or seen though it is. I see that flatpack has the same jack limitation. Is there a reason? 
I'm on 31 and everything works great with jack here. 
Thanks!

**Comment by agraef** [comment]
I'm not sure about the Flatpak version, but Fedora packages have been available on the OBS for a while, and they're supposed to work with Jack or without. In any case this is probably out of date for a while. :) Closing now.
