### ISSUE TITLE
SoundFiler's -resize flag not working

### ISSUE THREAD

**Issue by JamesNitsch** [agraef/purr-data#16]
When using SoundFiler to open a sample with more than 4000000 samples with the -resize flag, soundfiler throws an error: "error: soundfiler_read: truncated to 4000000 elements". This operation works without an error on the latest versions of PD vanilla (tested on 50.0 & 50.2).

OS: MacOS Catalina 10.15.3
Purr-data: Version 2.10.1 (20200311-rev.501d8b2b)

Steps to reproduce:
1. Create a new patch:
```
[bang]
|
[openpanel]
|
[read -resize $1 array1]
|
[soundfiler]

```
2. Open Wav file with > 4000000 samples into an array.
3. Observe that the array size is 4000000, and that the truncation error above is displayed in the console.

Any thoughts on the issue outlined above, and how to resolve would be appreciated!

**Comment by agraef** [comment]
@JamesNitsch This is only a mirror of the original repository here. Could you please submit this report upstream at https://git.purrdata.net/jwilkes/purr-data/-/issues? Thanks!
