### ISSUE TITLE
Adding external libraries fails with unhelpful message

### ISSUE THREAD

**Issue by sebeaumont** [agraef/purr-data#17]
I have tried to add the osc and iemnet pacakges into purr-data and although the system tries to load these are startup - all I get is an unhelpful "failed to load library..." message -- some diagnostics would be useful here.

BTW these libraries work fine with pd and replace the deprecated OSCx library which still ships with purr data -- I take it that even simple libraries need some porting effort to make them work in purr-data -- Are there plans for a nice external library installer like in Pd?

**Comment by agraef** [comment]
@sebeaumont This is only a mirror of the original repository here. Could you please submit this report upstream at https://git.purrdata.net/jwilkes/purr-data/-/issues? Thanks!
