### ISSUE TITLE
[bug fix/docs] agraef - purr-data. problems in the pre-requirements for ubuntu linux 22.04 lts

### ISSUE THREAD

**Issue by tiagomoraismorgado** [agraef/purr-data#23]
#### [bug fix/docs] agraef/purr-data -> problems in the pre-requirements for ubuntu linux 22.04 lts #23 

<b>in the readme.md file:</b>

<small><b>the some of the following packages are outdated in ubuntu 22.04 lts</b><small>

      sudo apt-get install bison flex automake libasound2-dev \
      libjack-jackd2-dev libtool libbluetooth-dev libgl1-mesa-dev \
      libglu1-mesa-dev libglew-dev libmagick++-dev libftgl-dev \
      libgmerlin-dev libgmerlin-avdec-dev libavifile-0.7-dev \
      libmpeg3-dev libquicktime-dev libv4l-dev libraw1394-dev \
      libdc1394-22-dev libfftw3-dev libvorbis-dev ladspa-sdk \
      dssi-dev tap-plugins invada-studio-plugins-ladspa blepvco \
      swh-plugins mcp-plugins cmt blop slv2-jack omins rev-plugins \
      libslv2-dev dssi-utils vco-plugins wah-plugins fil-plugins \
      mda-lv2 libmp3lame-dev libspeex-dev libgsl0-dev \
      portaudio19-dev liblua5.3-dev python-dev libsmpeg0 libjpeg62-turbo \
      flite1-dev libgsm1-dev libgtk2.0-dev git libstk0-dev \
      libfluidsynth-dev fluid-soundfont-gm byacc \
      python3-markdown

<small>**the list was made bearing ubuntu bionic and bionic beaver in mind**</small>
<small>**please feel free to fix this**</small>

<small>**looking forwards**</small>
<small>***kind regards***</small>
<small>*T.*</small>

**Comment by agraef** [comment]
Yes, but that's only in the README. The packages that we distribute here and via the OBS will have the right dependencies.

If you can update the list and send a PR for that, I'll be happy to merge it. Or you can go to https://git.purrdata.net/jwilkes/purr-data and report the issue there.
