### ISSUE TITLE
Avast 

### ISSUE THREAD

**Issue by waseltzer** [agraef/purr-data#27]
purr-data is flagged with IDP.Generic by Avast anti-virus 23.8.6078 (build 23.8.8416.762) (Windows 11)

**Comment by saaagar10** [comment]
@waseltzer can you  elaborate the issue .

**Comment by waseltzer** [comment]
Tired to install https://www.purrdata.net/
purr-data is flagged with IDP.Generic by Avast anti-virus 23.8.6078 (build 23.8.8416.762) (Windows 11)

**Comment by agraef** [comment]
> Tired to install https://www.purrdata.net/

That website is outdated. Current downloads are available here: https://github.com/agraef/purr-data/releases

> purr-data is flagged with IDP.Generic by Avast anti-virus 23.8.6078 (build 23.8.8416.762) (Windows 11)

Running the 2.19.3 and 2.19.4-rc3 installers through https://www.virustotal.com didn't detect anything, so closing.
