### ISSUE TITLE
Unable to silently/unattended install with Windows installer.

### ISSUE THREAD

**Issue by 3hQyrpzdAWztAOoXJhsd** [agraef/purr-data#29]
1. Download the 2.19.3 installer from https://github.com/agraef/purr-data/releases/download/2.19.3/purr-data-2.19.3-mingw-x86_64.zip. 
2. Extract the exe file from the zip. 
3. Run the exe with the following switches:

`Purr-Data-2.19.3-20230725-rev.e9fca4f8-x86_64.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-`

I'd expect the installer to run without an UI or prompt and install, but you get a popup saying **Note: The installation will now start**. with an option to click OK. 

![image](https://github.com/agraef/purr-data/assets/152532085/0a1d115f-8a40-4e13-a093-76b13d4f3713)

I've tried creating an answer file, but it didn't help. Going through the documentation at https://jrsoftware.org/ishelp/index.php?topic=setupcmdline I can't see any other useful option to suppress the prompt. 

Is this intentional, a bug, or am I missing something to suppress it.

**Comment by agraef** [comment]
Should be fixed in https://github.com/agraef/purr-data/releases/tag/2.19.4-rc3.

**Comment by agraef** [comment]
I mean, what we have now will still requires clicking Ok (or pressing Return) twice. I'm not sure how to modify the inno setup configuration to also get rid of these, but maybe that's good enough for you?

**Comment by agraef** [comment]
Ah yes, I see. We'll have to use SuppressibleMsgBox in the setup. Will do. Until then, reopening.

**Comment by agraef** [comment]
Fixed in rev. https://github.com/agraef/purr-data/commit/023a9456ac72e5dda4b831b8f83703654029a4aa.

**Comment by agraef** [comment]
Actually, fixed in https://github.com/agraef/purr-data/commit/d121a301e5fa42098d09ce3e9fd8af8b4eb0b5e4. (For some reason, the uninstaller keeps changing names when the installer runs unattended. So I had to modify the inno script to find it.)

**Comment by agraef** [comment]
Latest version now in rev. 7e1281b4167b76b717b3702ff45e4060d165e777. You should soon be able to grab the installer from the Actions tab if you want to give it a go before RC4 comes out.
