### ISSUE TITLE
Add release for Raspberry Pi OS? (Bookworm)

### ISSUE THREAD

**Issue by artbazz** [agraef/purr-data#30]
Hi,
i've struggled for a while trying to install the Raspbian 11 package on my Raspberry Pi 4 running Raspberry Pi OS (based on Debian 12 Bookworm), with no luck
Could you add a package for Raspberry Pi OS?
Thank you!
Arthur

**Comment by agraef** [comment]
Sorry, I already had Raspbian 12 in my test builds, but not at https://build.opensuse.org/project/show/home:aggraef:purr-data-jgu. I've added it now.
