### ISSUE TITLE
Outdated Dependencies and Incomplete Build Process.

### ISSUE THREAD

**Issue by AnirudhHanda** [agraef/purr-data#32]
The current build process for purr-data is encountering numerous obstacles due to outdated dependencies and incomplete documentation. This issue significantly hampers the setup process and obstructs contributors from effectively building the project. Below are the errors encountered during the attempted build:

Unable to locate package libdc1394-22-dev
Package 'slv2-jack' has no installation candidate
Package 'libslv2-dev' has no installation candidate
Package 'python-dev' has no installation candidate
Package 'libjpeg62-turbo' has no installation candidate
These errors indicate missing or deprecated packages which are crucial for the build process. As a result, users are unable to proceed with setting up purr-data successfully.

Action Required:

Update the build documentation to reflect the current dependencies and requirements accurately.
Address the missing or deprecated packages to ensure a smooth build process.
Provide clear instructions or alternatives for resolving these dependency issues.
Ensure that the build process is well-documented and accessible to all contributors.
Impact:
The current state of the build process poses significant barriers to entry for potential contributors. Resolving these issues will not only streamline the setup process but also encourage greater participation and collaboration within the project.

Proposed Solution:

Update the project's documentation repository with accurate information regarding dependencies and build instructions.
Conduct thorough testing to verify that the build process is functional and error-free.
Encourage community feedback and contributions to continuously improve the build process.
Addressing these concerns will enhance the accessibility and usability of purr-data, facilitating a more seamless experience for both developers and users.

**Comment by agraef** [comment]
I guess that you're referring to the information in the README? Yes, that's outdated, but at least provides you with a starting point. Package names vary wildly between different distributions, and change with new releases of the same distro all the time. No matter what we put into the README file, it won't work for everyone, not even for the majority of people. But I agree that the Linux section of the README could be improved, I just don't have the time. If you'd like to contribute something, please send me a PR and I'll look at it. :)

Note that in fact we *have* a "functional and error-free" build process in the form of the Debian source package in debuild/debian, and our [OBS builds](https://build.opensuse.org/project/show/home:aggraef:purr-data-jgu) covering a wide range of different Linux distributions. I always keep these up-to-date, as I see errors in the build logs as soon as some dependency changes or anything else breaks. In particular, if you need accurate information on what the current build dependencies are, look at the debuild/debian/control file. You can even build a Debian package straight from the source with `cd debuild && make debchange && make deb-us`, simple as that.

**Comment by agraef** [comment]
Ok, after re-reading your remarks, for me it it all boils down to the the dependencies list being outdated. Because the build process *is* already documented extensively in the [Installation](https://github.com/agraef/purr-data/wiki/Installation) wiki page, and our build process *is* already being tested thoroughly through the GH CI and OBS builds.

I've now added an issue about the information in the README in #43, so closing this one. As I said, feel free to submit a PR for updating that dependency list, that would be appreciated.
