### ISSUE TITLE
The atan2 patch does not mention any arguments

### ISSUE THREAD

**Issue by ayushanand308** [agraef/purr-data#36]
The argument section of atan2 should have a float, but it shows none instead in the help patch.

**Comment by msudipta888** [comment]
can i solve this issue

**Comment by agraef** [comment]
Sure. Send a PR and I'll look at it.

**Comment by msudipta888** [comment]
can you add more information about this issue

**Comment by agraef** [comment]
Fixed in rev. https://github.com/agraef/purr-data/commit/4c804867c4d742b513958fcdc7bf20188c9bc655.
