### ISSUE TITLE
i can't install these package for the tatest version of ubuntu

### ISSUE THREAD

**Issue by scqar-cyb** [agraef/purr-data#53]
it's said that all version are becamed obsolete.

**Comment by agraef** [comment]
I suspect that you downloaded the Ubuntu 22.04 LTS package from the Releases page, right? You'll need to download the right package for your Ubuntu version on the [OBS](https://software.opensuse.org//download.html?project=home%3Aaggraef%3Apurr-data-jgu&package=purr-data) instead. (You may also need some dependencies from our OBS repo that are not in the official Ubuntu repos any more. You can find all of these in in the [purr-data-jgu](https://build.opensuse.org/project/show/home:aggraef:purr-data-jgu) project on the OBS.)

Please also check the wiki for detailed installation instructions: https://github.com/agraef/purr-data/wiki/Installation
