### ISSUE TITLE
2.20.0+ELSE?

### ISSUE THREAD

**Issue by porres** [agraef/purr-data#54]
Hi, I see you have updated Purr Data to current 0.55-1 with all new features including the latest [expr] functionalities and etc... great!

This makes it possible to try the current ELSE release with Purr Data, because ELSE also has many many externals with multichannel connections support and I see you also have that now.

Ideally and eventually I/we could port the tcl/tk code and hopefully include this library over here for good, maybe a job for a Google Summer of Code project?

Note that the code and many other things have changed since last time you worked on this. There are many many new objects of course, but also a new build system. I also ended up removing some of the things you included, like the compat.h file, but we can easily put it back

**Comment by porres** [comment]
Also, I am assuming externals need to be compiled specially for Purr Data the same way that it happens for Pd-L2ork? 

See https://github.com/pd-l2ork/pd-l2ork/issues/61

**Comment by agraef** [comment]
Unfortunately, this isn't going to happen anytime soon. The main issue is that I couldn't find anyone willing to port the substantial amount of gui code that's in there, and I just don't have the time to do it myself.

I will give the latest cyclone another go, though, maybe some time during GSoC 2025. There we should have at least some existing JS gui code that I can reuse, so this should be a whole lot easier.

**Comment by porres** [comment]
I wasn't considering the gui port for now, and is it correct that it needs to be compiled for purr data? We can't just use vanilla binaries right?

**Comment by agraef** [comment]
> We can't just use vanilla binaries right?

No, that won't work. And I suspect that ELSE uses parts of Pd's non-public APIs which may be different in purr-data, so there's likely a substantial porting effort involved.

Also, in any case a major roadblock for any porting effort is the custom and outdated pd-lua version that you ship with ELSE. If it's still possible to build ELSE without that, then we can probably work around that.

But there is not a single reason why you should be shipping pd-lua with ELSE these days. purr-data uses the upstream version, as does plugdata. And for vanilla, thanks to Ben's work we now have our own Deken packages of pd-lua which are built automatically with each pd-lua release and are thus always up-to-date.

Hence this will also affect vanilla Pd users who face the choice between installing and running ELSE or the current pd-lua; they can't do both at the same time. I told you that this was going to be a problem. Please remove pd-lua from ELSE, that will make live much easier for vanilla users wishing to use both ELSE and pd-lua.
