### ISSUE TITLE
Purr Data GUI frozen and no menu with Ubuntu 24.04

### ISSUE THREAD

**Issue by transistorkreis** [agraef/purr-data#56]
Hi there,

I switched to Ubuntu Studio 24.04.1 LTS and installed it from scratch. And I installed Purr Data that I was using with Ubuntu Studio 22.10 before. Therefore, I added the aggraef:/purr-data-jgu repository and installed purr-data via apt as described for xUbuntu 24.04 here:

[https://software.opensuse.org/download/package?package=purr-data&project=home%3Aaggraef%3Apurr-data-jgu](https://software.opensuse.org/download/package?package=purr-data&project=home%3Aaggraef%3Apurr-data-jgu)

Unfortunately, I'm facing the following two problems:

1. Purr Data starts up very slowly and the GUI is a kind of frozen for few minutes until the error message "error: audio I/O stuck... closing audio" is output. Then the GUI is working again, i.e. I can change slider values, for instance. This issue also occurs if there is an audio interface attached with an active usb audio connection via Pipewire. Purr Data is not listed in the Carla patchbay.
2. There is no menu. Please find attached a screenshot. Respectively, I cannot change or have a look at the audio settings. The cat icon only lists window related entries for e.g. minimizing the window.

Any ideas how to solve these issues? I couldn't find any posts regarding this.

Thank you in advance!
![purr-data](https://github.com/user-attachments/assets/2289dfab-ba76-4e51-a9c3-da071a84931b)

**Comment by transistorkreis** [comment]
After patching Purr Data's nw.js as given in the installation instructions I was able to adjust the audio settings. This also seems to fix the frozen GUI issue.

**Comment by agraef** [comment]
Hmm, that's interesting. Which nw.js version do you use now?
